### ISSUE TITLE
Driving agent reacting to the future network

### ISSUE THREAD

**Issue by agrignard** [agrignard/ReChamp#38]
The driving agent are not yet reacting the future network.

I am not sure who was suppose to implement it, it seems that the number of lanes is taking in account but the closing of the road in front of the grand palais for instance is not implemented.

What needs to be implemented:

- [ ] Dynamic lanes
- [ ] Closing lanes (devant le grand palais)
- [ ] New lanes (palce de la concorde par exemple)

**Comment by tnguyenh** [comment]
For the lane there is nothing more to do since the lane is constantly updated for each car. For the disappearing and appearing, only the cars which recompute a new path consider the new network (Patrick correct me if I'm wrong). The agents that are already following a path are not updated.

Also right now updateSimuState does not work as intended (when you press space twice, the road does not reappear).

First we need to know what should happen when:

- closing lanes: 
* for agents already on a closed road: should they vanish ? Or be teleported to another road ? or continue as if the road was still there ?
* for agents not on a closed road, should they recompute their path ? when ? It would be a problem if the simulation freezes because every agents recompute their path in the same time.

- opening lanes:
* not much need to be done, since all the path computed before are still valid. Anyway, it may take time before vehicles use again the new roads. Should all agents recompute a new path ?

For both points, what kind of effect (in term of vizualisation) do we want ? 

My proposal: each time step a proportion of agents is updated. 
* If the agent is on a road that disappeared, with replace it somewhere else (as if he had reached is destination). 
* then the path is recomputed
with this process all agents will be updated. The agents on a road that disappeared will slowing vanish (eye candy !)

**Comment by tnguyenh** [comment]
OK done. I added a fading effect, maybe the mix of the two is too much (vanishing and fading).

**Comment by agrignard** [comment]
done you mean everything is implemented? 

I still see that on the concorde they are using a wrong road but this is because it's not in the road_osm 

For the vanishing fading did you push it?

**Comment by ptaillandier** [comment]
Salut,

J'ai un peu modifié le code pour être sûr que les voitures passaient plus
sur les routes interdites (méthode bourrine, mais comme on a pas beaucoup
de voiture cela passe).
J'ai légèrement adapté le fading effect (juste pour être compatible avec
mon truc, Tri, tu peux regarder pour voir si j'ai pas tout dénaturé).

Le lun. 20 janv. 2020 à 07:48, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
ok nickel ca à l'ari de bien marcher. Du coup j'ai un epu du mal à suivre toute les lignes de code donc je vous fait confiance à 200%. Par eemple il ya des path qui ont été créer en dur dasn des csv, c'etait pour tester ou c'est vraiment utilisé?


 Il ya en revanche plusieurs modèles maintenant c'est normal?

**Comment by ptaillandier** [comment]
argh.... j'ai commité des trucs en trop. Je nettoie tout ça.

Le lun. 20 janv. 2020 à 15:18, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
Oui c'est quoi rechamp2 et 3 ?

En fait t'as pas mal changé le comportement. Pour le fading, j'avais fait exprès de laisser les voitures continuer sur les rues fantômes le temps qu'elle disparaisse. A voir quel effet vous préférez, là j'aime moins quand elles se bloquent en disparaissant.

Le truc que t'as enlevé au début (update_cars) c'était pour mettre à jour petit à petit les voitures, et pas toutes d'un coup.

**Comment by tnguyenh** [comment]
oui, plus un petit bout ailleurs. Pour le framerate j'ai l'impression que y'a rien qui soit vraiment un problème. Je peux arranger le code, utiliser la manière de Patrick pour faire l'update et garder les caisses qui fadent tranquille à la fin de leur trajectoire. Il n'y a pas besoin en fait de les faire updater petit à petit, ça n'a pas l'air de killer le framerate.

Petit complément d'explication pour la méthode d'update que j'ai utilisée: Patrick j'ai l'impression que dans ta méthode le recalcul ne se fait que quand tu passes de avant à après. Mais en fait c'est bien aussi de recalculer le chemin quand tu passes de après à avant, car les véhicules peuvent à nouveau emprunter les routes qui ne sont plus fantômes. Du côté de la simul, j'ai l'impression que c'est plus visuel car les routes se remplissent plus vite.

En plus, normalement il devrait y avoir aussi des routes qui apparaissent après l'intervention (sur la Concorde, mais ça ne le fait pas dans le shape_file actuel) et donc qui disparaissent quand on revient à l'état avant. Donc dans les deux cas (avant et après) il doit y avoir des routes qui apparaissent et disparaissent, et l'update devrait se passer de la même manière que l'on passe de avant à après ou de après à avant.

Patrick, j'ai pas bien capté comment ça marche use_cache false. C'est pas clair dans la doc.

**Comment by agrignard** [comment]
on doit etre bon a priori a tester
